version: '3'

services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app

