name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag django-playground:$(date +%s)
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      url: https://legacy.triofan.com
    env:
      DOCKER_HOST: $TRIOFAN_DOCKER_HOST
      DOCKER_TLS_VERIFY: $TRIOFAN_DOCKER_TLS_VERIFY
    steps:
      - run: mkdir -p ~/.docker
      - run: echo "$SWARM_TLSCACERT" > ~/.docker/ca.pem
      - run: echo "$SWARM_TLSCERT" > ~/.docker/cert.pem
      - run: echo "$SWARM_TLSKEY" > ~/.docker/key.pem
      - run: docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - run: docker stack deploy -c docker-compose.yml legacy --with-registry-auth
